# -*- coding: utf-8 -*-
"""Edicion 8 slabs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Y_RcuzjTV-pVyd8fDw_3D7HklOQbne3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Ruta al archivo de texto
file_path = r"C:\Users\rodri\Downloads\8 SLABS modificado.txt"

# Leer el archivo de texto con el delimitador de tabulación
data = pd.read_csv(file_path, delimiter='\t')

# Extraer las frecuencias y magnitudes
freq1 = data['FREQ1.GHZ'] * 1e9
linmag1 = data['LINMAG1'] ** 2
linmag2 = data['LINMAG2'] ** 2

# Coeficientes
d = 0.00155
w = 0.02286  #real
#w = 0.007
c = 3e8
#l_val = [9.29e-3, 8.95e-3, 8.96e-3, 9.11e-3, 10.46e-3, 9.56e-3, 9.04e-3]   #como en el papel
l_val = [9.04e-3 , 9.56e-3, 10.46e-3, 9.11e-3, 8.96e-3, 8.95e-3, 9.29e-3]
#l_val = [9.04e-3 , 9.56e-3, 10.46e-3, 9.11e-3, 8.96e-3, 8.95e-3, 9.29e-3]
e = 5 + 0.01 * 1j  # Permitividad del medio    4.99191008964589+0.3790427167580642j
e=4+0.001*1j

# Vectores
v_val = np.linspace(1e9, 12e9, 500)
R_values = np.zeros(len(v_val))
T_values = np.zeros(len(v_val))

for i in range(len(v_val)):
    v = v_val[i]
    k = 2 * np.pi * (np.sqrt((v**2-(c/(2*w))**2) + 0 * 1j)) / c
    q = 2 * np.pi * (np.sqrt((e*v**2-(c/(2*w))**2) + 0 * 1j)) / c

    # Elementos de matriz M_slab
    M11 = np.cos(q * d) + 1j / 2 * (q / k + k / q) * np.sin(q * d)
    M22 = np.cos(q * d) - 1j / 2 * (q / k + k / q) * np.sin(q * d)
    M12 = 1j / 2 * ((q / k - k / q) * np.sin(q * d))
    M21 = -1j / 2 * ((q / k - k / q) * np.sin(q * d))

    M_slab = np.array([[M11, M12], [M21, M22]])

    # Inicialización de la matriz total
    M_Total = np.eye(2, dtype=complex)

    # Elementos de matriz M_vacio y multiplicación de matrices
    for p in range(len(l_val)):
        M_Total = np.matmul(M_Total, M_slab)
        l = l_val[p]
        M_vacio = np.array([[np.exp(1j * k * l), 0], [0, np.exp(-1j * k * l)]])
        M_Total = np.matmul(M_Total, M_vacio)

    # Multiplicación final con M_slab
    M_Total = np.matmul(M_Total, M_slab)

    # Calculo coeficientes de R y T
    R = np.abs(M_Total[1, 0])**2 / np.abs(M_Total[1, 1])**2
    T = 1 / np.abs(M_Total[1, 1])**2


    R_values[i] = R
    T_values[i] = T

# Graficar R vs v
plt.figure(figsize=(12, 6))

#plt.subplot(1, 2, 1)
plt.plot(v_val, R_values, color='b', label='Teorico')
plt.plot(freq1, linmag1, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('|R|')
plt.title('Coeficiente de Reflexión (|R|) vs Frecuencia (v)')
plt.xlim(1, 12e9)
plt.ylim(0,1.5)
plt.grid(True)
plt.legend()


# Graficar T vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, T_values, color='b', label='Teorico')
plt.plot(freq1, linmag2, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('|T|')
plt.title('Coeficiente de Transmision (|T|) vs Frecuencia (v)')
plt.xlim(1, 12e9)
plt.ylim(0,1.5)
plt.grid(True)
plt.legend()

#Error respecto a R

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

# Ruta al archivo de texto
file_path = r"C:\Users\rodri\Downloads\8 SLABS modificado.txt"

# Leer el archivo de texto con el delimitador de tabulación
data = pd.read_csv(file_path, delimiter='\t')

# Extraer las frecuencias y magnitudes
freq1 = data['FREQ1.GHZ'] * 1e9
linmag1 = data['LINMAG1'] ** 2
linmag2 = data['LINMAG2'] ** 2

# Coeficientes
d = 0.00155
w = 0.02286  #real
c = 3e8
#l_val = [9.29e-3, 8.95e-3, 8.96e-3, 9.11e-3, 10.46e-3, 9.56e-3, 9.04e-3]   #como en el papel
l_val = [9.04e-3 , 9.56e-3, 10.46e-3, 9.11e-3, 8.96e-3, 8.95e-3, 9.29e-3]
# Vectores
v_val = np.linspace(6.6e9, 12e9, 100 )

def calcular_RT(e_real, e_imag):
    e = e_real + e_imag * 1j
    R_values = np.zeros(len(v_val))
    T_values = np.zeros(len(v_val))
    for i in range(len(v_val)):
        v = v_val[i]
        k = 2 * np.pi * (np.sqrt((v**2 - (c / (2 * w))**2) + 0 * 1j)) / c
        q = 2 * np.pi * (np.sqrt((e * v**2 - (c / (2 * w))**2) + 0 * 1j)) / c

        # Elementos de matriz M_slab
        M11 = np.cos(q * d) + 1j / 2 * (q / k + k / q) * np.sin(q * d)
        M22 = np.cos(q * d) - 1j / 2 * (q / k + k / q) * np.sin(q * d)
        M12 = 1j / 2 * ((q / k - k / q) * np.sin(q * d))
        M21 = -1j / 2 * ((q / k - k / q) * np.sin(q * d))

        M_slab = np.array([[M11, M12], [M21, M22]])

        # Inicialización de la matriz total
        M_Total = np.eye(2, dtype=complex)

        # Elementos de matriz M_vacio y multiplicación de matrices

        for p in range(7):
            M_Total = np.matmul(M_Total, M_slab)
            l = l_val[p]
            M_vacio = np.array([[np.exp(1j * k * l), 0], [0, np.exp(-1j * k * l)]])
            M_Total = np.matmul(M_Total, M_vacio)

        M_Total = np.matmul(M_Total, M_slab)
        # Calculo coeficientes de R y T
        R = np.abs(M_Total[1, 0])**2 / np.abs(M_Total[1, 1])**2
        T = 1 / np.abs(M_Total[1, 1])**2

        R_values[i] = R
        T_values[i] = T
    return R_values, T_values

def error(params):
    e_real, e_imag = params
    R_teorico, _ = calcular_RT(e_real, e_imag)
    # Seleccionar solo los datos a partir de 6.6 GHz
    freq_mask = freq1 >= 6.6e9
    freq1_filtered = freq1[freq_mask]
    linmag1_filtered = linmag1[freq_mask]
    v_val_filtered = v_val
    R_teorico_filtered = R_teorico
    error = np.sum((R_teorico_filtered - np.interp(v_val_filtered, freq1_filtered, linmag1_filtered))**2)
    return error

# Valores iniciales para epsilon
initial_guess = [1, 0.001]

# Optimización
result = minimize(error, initial_guess, method='Nelder-Mead')
e_opt_real, e_opt_imag = result.x
e_opt = e_opt_real + e_opt_imag * 1j
opt_error = result.fun

# Calcular reflexión y transmisión con epsilon optimizado
R_opt, T_opt = calcular_RT(e_opt_real, e_opt_imag)

#Calcular suma
suma = R_opt + T_opt

#Calcular absorcion
absorcion = 1 - R_opt - T_opt
absorcionVNA = 1 - linmag1 - linmag2
# Graficar R vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, R_opt, color='b', label='Teórico (Optimizado)')
plt.plot(freq1, linmag1, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('|R|')
plt.title('Coeficiente de Reflexión (|R|) vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

# Graficar T vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, T_opt, color='b', label='Teórico (Optimizado)')
plt.plot(freq1, linmag2, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('|T|')
plt.title('Coeficiente de Transmisión (|T|) vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

plt.show()

# Graficar Absorcion vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, absorcion, color='b', label='Teórico (Optimizado)')
plt.plot(freq1, absorcionVNA, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('Absorcion')
plt.title('Absorcion) vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
#plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

# Graficar Suma vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, suma, color='b', label='Teórico (Optimizado)')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('Suma')
plt.title('Suma) vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

plt.show()

print(f"Valor optimizado de epsilon: {e_opt}")
print(f"Error optimizado: {opt_error}")

"Nelder-Mead"
Valor optimizado de epsilon: (4.99191008964589+0.3790427167580642j)
Error optimizado: 12.12304285679985

Valor optimizado de epsilon: (4.357416479873762-0.02001809506508289j)
Error optimizado: 4.901785989502279

"BFGS"
Valor optimizado de epsilon: (4.99192120763561+0.3790488839056073j)
Error optimizado: 12.123042855582094

ahora
Valor optimizado de epsilon: (5.540077425875838+0.4077109241475806j)
Error optimizado: 12.354338521302424

#Error respecto a T

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

# Ruta al archivo de texto
file_path = r"C:\Users\rodri\Downloads\8 SLABS modificado.txt"

# Leer el archivo de texto con el delimitador de tabulación
data = pd.read_csv(file_path, delimiter='\t')

# Extraer las frecuencias y magnitudes
freq1 = data['FREQ1.GHZ'] * 1e9
linmag1 = data['LINMAG1'] ** 2
linmag2 = data['LINMAG2'] ** 2

# Coeficientes
d = 0.00155
w = 0.02286  #real
c = 3e8
#l_val = [9.29e-3, 8.95e-3, 8.96e-3, 9.11e-3, 10.46e-3, 9.56e-3, 9.04e-3]   #como en el papel
l_val = [9.04e-3 , 9.56e-3, 10.46e-3, 9.11e-3, 8.96e-3, 8.95e-3, 9.29e-3]
# Vectores
v_val = np.linspace(6.6e9, 12e9, 100)

def calcular_RT(e_real, e_imag):
    e = e_real + e_imag * 1j
    R_values = np.zeros(len(v_val))
    T_values = np.zeros(len(v_val))
    for i in range(len(v_val)):
        v = v_val[i]
        k = 2 * np.pi * (np.sqrt((v**2 - (c / (2 * w))**2) + 0 * 1j)) / c
        q = 2 * np.pi * (np.sqrt((e * v**2 - (c / (2 * w))**2) + 0 * 1j)) / c

        # Elementos de matriz M_slab
        M11 = np.cos(q * d) + 1j / 2 * (q / k + k / q) * np.sin(q * d)
        M22 = np.cos(q * d) - 1j / 2 * (q / k + k / q) * np.sin(q * d)
        M12 = 1j / 2 * ((q / k - k / q) * np.sin(q * d))
        M21 = -1j / 2 * ((q / k - k / q) * np.sin(q * d))

        M_slab = np.array([[M11, M12], [M21, M22]])

        # Inicialización de la matriz total
        M_Total = np.eye(2, dtype=complex)

        # Elementos de matriz M_vacio y multiplicación de matrices
        for p in range(7):
            M_Total = np.matmul(M_Total, M_slab)
            l = l_val[p]
            M_vacio = np.array([[np.exp(1j * k * l), 0], [0, np.exp(-1j * k * l)]])
            M_Total = np.matmul(M_Total, M_vacio)

        M_Total = np.matmul(M_Total, M_slab)
        # Calculo coeficientes de R y T
        R = np.abs(M_Total[1, 0])**2 / np.abs(M_Total[1, 1])**2
        T = 1 / np.abs(M_Total[1, 1])**2

        R_values[i] = R
        T_values[i] = T
    return R_values, T_values

def error(params):
    e_real, e_imag = params
    _, T_teorico = calcular_RT(e_real, e_imag)
    # Seleccionar solo los datos a partir de 6.6 GHz
    freq_mask = freq1 >= 6.6e9
    freq1_filtered = freq1[freq_mask]
    linmag2_filtered = linmag2[freq_mask]
    v_val_filtered = v_val
    T_teorico_filtered = T_teorico
    error = np.sum((T_teorico_filtered - np.interp(v_val_filtered, freq1_filtered, linmag2_filtered))**2)
    return error

# Valores iniciales para epsilon
initial_guess = [1, 0.001]

# Optimización
result = minimize(error, initial_guess, method='Nelder-Mead')
e_opt_real, e_opt_imag = result.x
e_opt = e_opt_real + e_opt_imag * 1j
opt_error = result.fun

# Calcular reflexión y transmisión con epsilon optimizado
R_opt, T_opt = calcular_RT(e_opt_real, e_opt_imag)

#Calcular suma
suma = R_opt + T_opt

#Calcular absorcion
absorcion = 1 - R_opt - T_opt
absorcionVNA = 1 - linmag1 - linmag2
# Graficar R vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, R_opt, color='b', label='Teórico (Optimizado)')
plt.plot(freq1, linmag1, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('|R|')
plt.title('Coeficiente de Reflexión (|R|) vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

# Graficar T vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, T_opt, color='b', label='Teórico (Optimizado)')
plt.plot(freq1, linmag2, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('|T|')
plt.title('Coeficiente de Transmisión (|T|) vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

plt.show()

# Graficar Absorcion vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, absorcion, color='b', label='Teórico (Optimizado)')
plt.plot(freq1, absorcionVNA, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('Absorción')
plt.title('Absorción vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

# Graficar Suma vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, suma, color='b', label='Teórico (Optimizado)')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('Suma')
plt.title('Suma vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

plt.show()

print(f"Valor optimizado de epsilon: {e_opt}")
print(f"Error optimizado: {opt_error}")

#Suma
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

# Ruta al archivo de texto
file_path = r"C:\Users\rodri\Downloads\8 SLABS modificado.txt"

# Leer el archivo de texto con el delimitador de tabulación
data = pd.read_csv(file_path, delimiter='\t')

# Extraer las frecuencias y magnitudes
freq1 = data['FREQ1.GHZ'] * 1e9
linmag1 = data['LINMAG1'] ** 2
linmag2 = data['LINMAG2'] ** 2

# Coeficientes
d = 0.00155
w = 0.02286  #real
c = 3e8
#l_val = [9.29e-3, 8.95e-3, 8.96e-3, 9.11e-3, 10.46e-3, 9.56e-3, 9.04e-3]   #como en el papel
l_val = [9.04e-3 , 9.56e-3, 10.46e-3, 9.11e-3, 8.96e-3, 8.95e-3, 9.29e-3]
# Vectores
v_val = np.linspace(6.6e9, 12e9, 100)

def calcular_RT(e_real, e_imag):
    e = e_real + e_imag * 1j
    R_values = np.zeros(len(v_val))
    T_values = np.zeros(len(v_val))
    for i in range(len(v_val)):
        v = v_val[i]
        k = 2 * np.pi * (np.sqrt((v**2 - (c / (2 * w))**2) + 0 * 1j)) / c
        q = 2 * np.pi * (np.sqrt((e * v**2 - (c / (2 * w))**2) + 0 * 1j)) / c

        # Elementos de matriz M_slab
        M11 = np.cos(q * d) + 1j / 2 * (q / k + k / q) * np.sin(q * d)
        M22 = np.cos(q * d) - 1j / 2 * (q / k + k / q) * np.sin(q * d)
        M12 = 1j / 2 * ((q / k - k / q) * np.sin(q * d))
        M21 = -1j / 2 * ((q / k - k / q) * np.sin(q * d))

        M_slab = np.array([[M11, M12], [M21, M22]])

        # Inicialización de la matriz total
        M_Total = np.eye(2, dtype=complex)

        # Elementos de matriz M_vacio y multiplicación de matrices
        for p in range(7):
            M_Total = np.matmul(M_Total, M_slab)
            l = l_val[p]
            M_vacio = np.array([[np.exp(1j * k * l), 0], [0, np.exp(-1j * k * l)]])
            M_Total = np.matmul(M_Total, M_vacio)

        M_Total = np.matmul(M_Total, M_slab)
        # Calculo coeficientes de R y T
        R = np.abs(M_Total[1, 0])**2 / np.abs(M_Total[1, 1])**2
        T = 1 / np.abs(M_Total[1, 1])**2

        R_values[i] = R
        T_values[i] = T
    return R_values, T_values

def error(params):
    e_real, e_imag = params
    R_teorico, T_teorico = calcular_RT(e_real, e_imag)
    # Seleccionar solo los datos a partir de 6.6 GHz
    freq_mask = freq1 >= 6.6e9
    freq1_filtered = freq1[freq_mask]
    linmag1_filtered = linmag1[freq_mask]
    linmag2_filtered = linmag2[freq_mask]
    v_val_filtered = v_val
    R_teorico_filtered = R_teorico
    T_teorico_filtered = T_teorico
    error_R = np.sum((R_teorico_filtered - np.interp(v_val_filtered, freq1_filtered, linmag1_filtered))**2)
    error_T = np.sum((T_teorico_filtered - np.interp(v_val_filtered, freq1_filtered, linmag2_filtered))**2)
    return error_R + error_T

# Valores iniciales para epsilon
initial_guess = [1, 0.001]

# Optimización
result = minimize(error, initial_guess, method='Nelder-Mead')
e_opt_real, e_opt_imag = result.x
e_opt = e_opt_real + e_opt_imag * 1j
opt_error = result.fun

# Calcular reflexión y transmisión con epsilon optimizado
R_opt, T_opt = calcular_RT(e_opt_real, e_opt_imag)

#Calcular suma
suma = R_opt + T_opt

#Calcular absorcion
absorcion = 1 - R_opt - T_opt
absorcionVNA = 1 - linmag1 - linmag2
# Graficar R vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, R_opt, color='b', label='Teórico (Optimizado)')
plt.plot(freq1, linmag1, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('|R|')
plt.title('Coeficiente de Reflexión (|R|) vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
#plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

# Graficar T vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, T_opt, color='b', label='Teórico (Optimizado)')
plt.plot(freq1, linmag2, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('|T|')
plt.title('Coeficiente de Transmisión (|T|) vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

plt.show()

# Graficar Absorcion vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, absorcion, color='b', label='Teórico (Optimizado)')
plt.plot(freq1, absorcionVNA, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('Absorción')
plt.title('Absorción vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

# Graficar Suma vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, suma, color='b', label='Teórico (Optimizado)')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('Suma')
plt.title('Suma vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

plt.show()

print(f"Valor optimizado de epsilon: {e_opt}")
print(f"Error optimizado: {opt_error}")

#respecto a abs

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

# Ruta al archivo de texto
file_path = r"C:\Users\rodri\Downloads\8 SLABS modificado.txt"

# Leer el archivo de texto con el delimitador de tabulación
data = pd.read_csv(file_path, delimiter='\t')

# Extraer las frecuencias y magnitudes
freq1 = data['FREQ1.GHZ'] * 1e9
linmag1 = data['LINMAG1'] ** 2
linmag2 = data['LINMAG2'] ** 2

# Coeficientes
d = 0.00155
w = 0.02286  #real
c = 3e8
#l_val = [9.29e-3, 8.95e-3, 8.96e-3, 9.11e-3, 10.46e-3, 9.56e-3, 9.04e-3]   #como en el papel
l_val = [9.04e-3 , 9.56e-3, 10.46e-3, 9.11e-3, 8.96e-3, 8.95e-3, 9.29e-3]
# Vectores
v_val = np.linspace(6.6e9, 12e9, 100)

def calcular_RT(e_real, e_imag):
    e = e_real + e_imag * 1j
    R_values = np.zeros(len(v_val))
    T_values = np.zeros(len(v_val))
    for i in range(len(v_val)):
        v = v_val[i]
        k = 2 * np.pi * (np.sqrt((v**2 - (c / (2 * w))**2) + 0 * 1j)) / c
        q = 2 * np.pi * (np.sqrt((e * v**2 - (c / (2 * w))**2) + 0 * 1j)) / c

        # Elementos de matriz M_slab
        M11 = np.cos(q * d) + 1j / 2 * (q / k + k / q) * np.sin(q * d)
        M22 = np.cos(q * d) - 1j / 2 * (q / k + k / q) * np.sin(q * d)
        M12 = 1j / 2 * ((q / k - k / q) * np.sin(q * d))
        M21 = -1j / 2 * ((q / k - k / q) * np.sin(q * d))

        M_slab = np.array([[M11, M12], [M21, M22]])

        # Inicialización de la matriz total
        M_Total = np.eye(2, dtype=complex)

        # Elementos de matriz M_vacio y multiplicación de matrices
        for p in range(7):
            M_Total = np.matmul(M_Total, M_slab)
            l = l_val[p]
            M_vacio = np.array([[np.exp(1j * k * l), 0], [0, np.exp(-1j * k * l)]])
            M_Total = np.matmul(M_Total, M_vacio)

        M_Total = np.matmul(M_Total, M_slab)
        # Calculo coeficientes de R y T
        R = np.abs(M_Total[1, 0])**2 / np.abs(M_Total[1, 1])**2
        T = 1 / np.abs(M_Total[1, 1])**2

        R_values[i] = R
        T_values[i] = T
    return R_values, T_values

def error(params):
    e_real, e_imag = params
    R_teorico, T_teorico = calcular_RT(e_real, e_imag)
    absorcion_teorico = 1 - R_teorico - T_teorico
    # Seleccionar solo los datos a partir de 6.6 GHz
    freq_mask = freq1 >= 6.6e9
    freq1_filtered = freq1[freq_mask]
    linmag1_filtered = linmag1[freq_mask]
    linmag2_filtered = linmag2[freq_mask]
    absorcionVNA_filtered = 1 - linmag1_filtered - linmag2_filtered
    absorcion_teorico_filtered = absorcion_teorico
    error_absorcion = np.sum((absorcion_teorico_filtered - np.interp(v_val, freq1_filtered, absorcionVNA_filtered))**2)
    return error_absorcion

# Valores iniciales para epsilon
initial_guess = [1, 0.001]

# Optimización
result = minimize(error, initial_guess, method='Nelder-Mead')
e_opt_real, e_opt_imag = result.x
e_opt = e_opt_real + e_opt_imag * 1j
opt_error = result.fun

# Calcular reflexión, transmisión y absorción con epsilon optimizado
R_opt, T_opt = calcular_RT(e_opt_real, e_opt_imag)
absorcion_opt = 1 - R_opt - T_opt
absorcionVNA = 1 - linmag1 - linmag2

# Graficar R vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, R_opt, color='b', label='Teórico (Optimizado)')
plt.plot(freq1, linmag1, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('|R|')
plt.title('Coeficiente de Reflexión (|R|) vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
#plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

# Graficar T vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, T_opt, color='b', label='Teórico (Optimizado)')
plt.plot(freq1, linmag2, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('|T|')
plt.title('Coeficiente de Transmisión (|T|) vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

plt.show()

# Graficar Absorcion vs v
plt.figure(figsize=(12, 6))
plt.plot(v_val, absorcion_opt, color='b', label='Teórico (Optimizado)')
plt.plot(freq1, absorcionVNA, color='r', label='VNA')
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('Absorción')
plt.title('Absorción vs Frecuencia (v)')
plt.xlim(1e9, 12e9)
plt.ylim(0, 1.5)
plt.grid(True)
plt.legend()

plt.show()

print(f"Valor optimizado de epsilon: {e_opt}")
print(f"Error optimizado: {opt_error}")

