# -*- coding: utf-8 -*-
"""transmission_optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PeQZIoJgcTAr6avqkr12bZgZFqml9IxH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize

# 1. Carga de Datos del VNA
file_path = "vna_measurements.txt" # Nombre actualizado para el repositorio
data = pd.read_csv(file_path, delimiter='\t')

freq1 = data['FREQ1.GHZ'] * 1e9
linmag1 = data['LINMAG1'] ** 2
linmag2 = data['LINMAG2'] ** 2

# 2. Parámetros del Sistema Físico
d = 0.00155
w = 0.02286
c = 3e8
l_val = [9.04e-3, 9.56e-3, 10.46e-3, 9.11e-3, 8.63e-3, 8.95e-3, 9.29e-3] # Distancias
v_val = np.linspace(6.6e9, 12e9, 100)

# 3. Modelo Matemático (Matriz de Transferencia)
def calcular_RT(e_real, e_imag):
    e = e_real + e_imag * 1j
    R_values = np.zeros(len(v_val))
    T_values = np.zeros(len(v_val))

    for i in range(len(v_val)):
        v = v_val[i]
        k = 2 * np.pi * (np.sqrt((v**2 - (c / (2 * w))**2) + 0j)) / c
        q = 2 * np.pi * (np.sqrt((e * v**2 - (c / (2 * w))**2) + 0j)) / c

        M11 = np.cos(q * d) + 1j / 2 * (q / k + k / q) * np.sin(q * d)
        M22 = np.cos(q * d) - 1j / 2 * (q / k + k / q) * np.sin(q * d)
        M12 = 1j / 2 * ((q / k - k / q) * np.sin(q * d))
        M21 = -1j / 2 * ((q / k - k / q) * np.sin(q * d))

        M_slab = np.array([[M11, M12], [M21, M22]])
        M_Total = np.eye(2, dtype=complex)

        for p in range(7):
            M_Total = np.matmul(M_Total, M_slab)
            l = l_val[p]
            M_vacio = np.array([[np.exp(1j * k * l), 0], [0, np.exp(-1j * k * l)]])
            M_Total = np.matmul(M_Total, M_vacio)

        M_Total = np.matmul(M_Total, M_slab)

        R_values[i] = np.abs(M_Total[1, 0])**2 / np.abs(M_Total[1, 1])**2
        T_values[i] = 1 / np.abs(M_Total[1, 1])**2

    return R_values, T_values

# 4. Función de Error para la Optimización
def error(params):
    e_real, e_imag = params
    R_teorico, T_teorico = calcular_RT(e_real, e_imag)

    freq_mask = freq1 > 6.6e9
    freq1_filtered = freq1[freq_mask]
    linmag2_filtered = linmag2[freq_mask]

    T_teorico_filtered = T_teorico
    # Interpolación para alinear datos experimentales y teóricos
    error_val = np.sum((T_teorico_filtered - np.interp(v_val, freq1_filtered, linmag2_filtered))**2)
    return error_val

# 5. Ejecución de la Optimización (Nelder-Mead)
initial_guess = [1, 0.001]
result = minimize(error, initial_guess, method='Nelder-Mead')

e_opt_real, e_opt_imag = result.x
e_opt = e_opt_real + e_opt_imag * 1j
print(f"Valor optimizado de epsilon: {e_opt}")
print(f"Error optimizado: {result.fun}")